# fly.toml app configuration file generated for org-manager on 2025-04-14T13:26:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'org-manager'
primary_region = 'fra'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

# Section to run database migrations on deploy
[deploy]
  release_command = "bundle exec rails db:migrate"
